server:
  port: 8080

spring:
  application:
    name: weather-information-service

weather:
  api:
    key: {WEATHER_API_KEY}
    base-url: http://api.weatherapi.com/v1

logging:
  level:
    com.weather.service: DEBUG
